# Generated by Django 5.1.3 on 2024-11-26 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_bugreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_test_cases', models.IntegerField()),
                ('passed_test_cases', models.IntegerField()),
                ('failed_test_cases', models.IntegerField()),
                ('bugs_summary', models.JSONField()),
                ('observations', models.TextField()),
                ('recommendations', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_reports', to='api.project')),
            ],
            options={
                'db_table': 'testreport',
            },
        ),
    ]
