# Generated by Django 5.1.3 on 2024-11-27 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_testreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugreport',
            name='evidence',
            field=models.FileField(blank=True, null=True, upload_to='bug_reports/evidence/'),
        ),
    ]
