# Generated by Django 5.1.3 on 2024-11-27 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_bugreport_bug_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcoverage',
            name='feature_id',
            field=models.CharField(max_length=20),
        ),
    ]
