# Generated by Django 5.1.3 on 2024-12-08 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_testcoverage_feature_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
