# Generated by Django 5.1.3 on 2024-12-09 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='testcaseID',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
