# Generated by Django 5.1.3 on 2024-12-09 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_testcase_testcaseid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcoverage',
            name='feature_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
