# Generated by Django 5.1.3 on 2024-12-10 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_testcoverage_feature_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefectReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defect_id', models.CharField(max_length=10)),
                ('summary', models.TextField()),
                ('steps_to_reproduce', models.TextField()),
                ('severity', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], max_length=10)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed'), ('In Progress', 'Inprogress'), ('Fixed', 'Fixed')], default='Open', max_length=15)),
                ('evidence', models.FileField(blank=True, null=True, upload_to='defect_reports/evidence/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.project')),
            ],
            options={
                'db_table': 'defect_report',
            },
        ),
        migrations.DeleteModel(
            name='BugReport',
        ),
    ]
