# Generated by Django 5.1.3 on 2024-12-10 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_defectreport_delete_bugreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defectreport',
            name='defect_id',
            field=models.CharField(max_length=30),
        ),
    ]
