# Generated by Django 5.1.3 on 2024-12-10 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_defectreport_defect_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='defectreport',
            name='defect_detected_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='defectreport',
            name='defect_fixed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='defectreport',
            name='reopen_defect_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
