# Generated by Django 5.1.3 on 2024-12-10 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_defectreport_defect_detected_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testreport',
            old_name='bugs_summary',
            new_name='defect_summary',
        ),
    ]
