# Generated by Django 5.1.3 on 2024-12-17 20:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_rename_bugs_summary_testreport_defect_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCaseStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pass', 'Pass'), ('Fail', 'Fail'), ('Pending', 'Pending')], max_length=10)),
                ('recorded_at', models.DateField(default=django.utils.timezone.now)),
                ('testcase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='api.testcase')),
            ],
            options={
                'db_table': 'testcase_status',
                'unique_together': {('testcase', 'recorded_at')},
            },
        ),
    ]
